export const core = [
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2457483710&spec=640&img_type=jpg',
    name: '云竹',
    title: '创始人',
    org: 'Cloudery',
    desc: '这里是云竹，云蒸霞蔚，竹解虚心。对多彩的世界和可爱的你感到好奇，正在尝试从事互联网产品和网站开发相关工作。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2675256772&spec=640&img_type=jpg',
    name: '柒屹',
    title: '创始人',
    org: 'Cloudery',
    desc: '我是柒屹，柒星拱月，屹立不倒。从事互联网事业及网站开发工作，也在搞Java的一些东西。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=971995487&spec=640&img_type=jpg',
    name: '笔墨星河',
    title: '创始人&软件作者',
    org: '笔墨星河Ai写作',
    desc: '笔墨绘星河，书写属于自己的故事！',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=3014786442&spec=640&img_type=jpg',
    name: 'ZERO(0)',
    title: '成员',
    org: 'Cloudery',
    desc: '你知道吗，零是一切的开始。一个虽然没有qqvip但是专门挂群的人。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=953595252&spec=640&img_type=jpg',
    name: '信念',
    title: '成员',
    org: 'Cloudery',
    desc: '信马由缰，念兹在兹。主管云术生存战争服务器。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2770161886&spec=640&img_type=jpg',
    name: '暴躁月',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=1492657723&spec=640&img_type=jpg',
    name: 'mingh',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '管理icp.hair。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=190455549&spec=640&img_type=jpg',
    name: 'Daimaxue',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '互联网科技探索人员。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=3831212757&spec=640&img_type=jpg',
    name: 'Leech',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2047752264&spec=640&img_type=jpg',
    name: 'Serein.',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2054911074&spec=640&img_type=jpg',
    name: 'y_bowen',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2171587486&spec=640&img_type=jpg',
    name: '超级无敌暴龙战士',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '搞idc的。',
  },
  {
    avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=3067315092&spec=640&img_type=jpg',
    name: 'C8H806',
    title: '吉祥物',
    org: 'Cloudery',
    desc: '对的，这是一只比较凶的吉祥物',
  },
]
