export const core = [
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2457483710&spec=640&img_type=jpg',
    name: '云竹',
    title: '创始人',
    org: 'Cloudery',
    desc: '你好，这里是 YZ ，24岁，是学生，对有趣的世界和可能有趣的你感到好奇，热爱Tech和ACG文化，正在尝试从事互联网产品/Web开发相关工作。',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2675256772&spec=640&img_type=jpg',
    name: '柒屹',
    title: '创始人',
    org: 'Cloudery',
    desc: '我是柒屹，同时也是云术工作室重要成员之一，屹立不倒。从事互联网事业及Web开发工作，也在搞关于Java的一些东西',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=971995487&spec=640&img_type=jpg',
    name: '笔墨星河AI写作',
    title: '创始人&软件作者',
    org: '笔墨星河',
    desc: '笔墨绘星河，书写属于自己的故事！',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=3014786442&spec=640&img_type=jpg',
    name: 'ZERO(0)',
    title: '成员',
    org: 'Cloudery',
    desc: '管理云术生存战争服务器，同时也是云术工作室重要成员之一。',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=953595252&spec=640&img_type=jpg',
    name: '信念',
    title: '成员',
    org: 'Cloudery',
    desc: '管理云术生存战争服务器，同时也是云术工作室重要成员之一。',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2770161886&spec=640&img_type=jpg',
    name: '暴躁月',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=1492657723&spec=640&img_type=jpg',
    name: 'mingh',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=190455549&spec=640&img_type=jpg',
    name: 'Daimaxue',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=3831212757&spec=640&img_type=jpg',
    name: 'Leech',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2047752264&spec=640&img_type=jpg',
    name: 'Serein.',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2054911074&spec=640&img_type=jpg',
    name: 'y_bowen',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2171587486&spec=640&img_type=jpg',
    name: '超级无敌暴龙战士',
    title: '旁系成员',
    org: 'Cloudery',
    desc: '暂无描述',
  },
  {
    avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=3067315092&spec=640&img_type=jpg',
    name: 'C8H806',
    title: '吉祥物',
    org: 'Cloudery',
    desc: '暂无描述',
  },
]
