name: Build Test

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 10.6.1
    - name: Setup Node 
      uses: actions/setup-node@v4
      with:
        node-version: 22.11.0
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm build --if-present
